name: ConsoleSpawnMob
main: me.kapehh.ConsoleSpawnMob.ConsoleSpawnMob
author: kapehh
version: 1.0.0
commands:
    spawnmobx:
      usage: /<command> [ location <world> <x> <y> <z> / players <world> ] <radius> <count> <mob>
      description: